AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for personal-website-backend-dev

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
Resources:
  PersonalWebsiteTableDev:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PersonalWebsiteTableDev
      AttributeDefinitions:
        - AttributeName: personalWebsiteType
          AttributeType: S
        - AttributeName: sortValue
          AttributeType: S
      KeySchema:
        - AttributeName: personalWebsiteType
          KeyType: HASH
        - AttributeName: sortValue
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  PersonalWebsiteAPIDeploymentDev:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  PersonalWebsiteFunctionDev:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/{proxy+}"
            Method: ANY
            RestApiId: !Ref PersonalWebsiteAPIDeploymentDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonalWebsiteTableDev
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENV: Dev
          REGION: us-east-2
          TABLE_NAME: !Ref PersonalWebsiteTableDev

Outputs:
  PersonalWebsiteAPIDev:
    Description: API Gateway endpoint URL for Dev environment for First Function
    Value: !Sub "https://${PersonalWebsiteAPIDeploymentDev}.execute-api.${AWS::Region}.amazonaws.com/${PersonalWebsiteAPIDeploymentDev.Stage}/"
  PersonalWebsiteFunctionDev:
    Description: First Lambda Function ARN
    Value: !GetAtt PersonalWebsiteFunctionDev.Arn
  PersonalWebsiteFunctionDevIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt PersonalWebsiteFunctionDevRole.Arn