version: '3.8'
services:
 dynamodb:
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   networks:
     - backend
   ports:
     - "8000:8000"
   volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'

networks:
  backend:
    name: dynamodb-backend
