AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for personal-website-backend-stg

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
Resources:
  PersonalWebsiteTableStg:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PersonalWebsiteTableStg
      AttributeDefinitions:
        - AttributeName: personalWebsiteType
          AttributeType: S
        - AttributeName: sortValue
          AttributeType: S
      KeySchema:
        - AttributeName: personalWebsiteType
          KeyType: HASH
        - AttributeName: sortValue
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  PersonalWebsiteFunctionStg:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/{proxy+}"
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonalWebsiteTableStg
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENV: Stg
          REGION: us-east-2
          TABLE_NAME: !Ref PersonalWebsiteTableStg

Outputs:
  PersonalWebsiteAPIStg:
    Description: API Gateway endpoint URL for Stg environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stg/api"
  PersonalWebsiteFunctionStg:
    Description: First Lambda Function ARN
    Value: !GetAtt PersonalWebsiteFunctionStg.Arn
  PersonalWebsiteFunctionStgIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt PersonalWebsiteFunctionStgRole.Arn