AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for personal-website-backend-stg

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
    
Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    BinaryMediaTypes:
      - image/png
      - image/jpeg
      - image/gif
      - application/octet-stream
      - "multipart/form-data"
      - "multipart/*"
Resources:
  PersonalWebsiteTableLocal:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: PersonalWebsiteTable
  RestApiFunctionLocal:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: "/api/{proxy+}"
            Method: ANY
      Environment:
        Variables:
          ENV: Local
          REGION: us-east-2
          TABLE_NAME: PersonalWebsiteTable
          BUCKET_NAME: !Ref BucketName

Outputs:
  PersonalWebsiteAPILocal:
    Description: API Gateway endpoint URL for Dev environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/"
  RestApiFunctionLocal:
    Description: First Lambda Function ARN
    Value: !GetAtt RestApiFunctionLocal.Arn
  RestApiFunctionLocalIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt RestApiFunctionLocalRole.Arn